spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tcc_stock?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    poolName: hikariCP
    type: com.zaxxer.hikari.HikariDataSource
tcc:
  serializer: com.tcc.core.serializer.KryoSerializer
  recoverDelayTime: 128
  retryMax: 30
  scheduledDelay: 128
  scheduledThreadMax: 10
  repositorySupport: db
  tccDbConfig:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tcc?useUnicode=true&amp;characterEncoding=utf8&useSSL=false
    username: root
    password: root
mybatis:
  type-aliases-package: com.tcc.demo.springcloud.inventory.domain.entity
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    root: info
    tk.mybatis: info
    tcc.core: DEBUG
server:
  port: 8883
  servlet:
    context-path: /inventory-service
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true