spring:
  application:
    name: eureka-server
  freemarker:
    prefer-file-system-access: false
    
server:
  servlet:
    context-path: /
  port: 8761

logging:
  level:
    root: info
    
#eureka:
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  server:
#    enable-self-preservation: false #关闭自我保护机制
#    eviction-interval-timer-in-ms: 4000 #清理间隔
    
eureka:
  instance:
    hostname: ${hostname:localhost}
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 6
  server:
    peerEurekaNodesUpdateIntervalMs: 60000
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 5000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    eurekaServiceUrlPollIntervalSeconds: 60